### ISSUE TITLE
Добавяне на лиценз

### ISSUE THREAD

**Issue by mitio** [pdpetrov/data-viz#1]
Както и в хранилището, така и на сайта, например във футъра, е добре да е упоменато лицензионно споразумение, указващо дали и как може да се преизползват данните и визуализациите, направени на портала. Ако такова не е упоменато, по подразбиране всичко е copyrighted и нищо не може да се преизползва, което противоречи на идеята за отвореност.

В хранилището това обикновено става с файл `LICENSE`. Ето пример от хранилището [governmentbg/opendata](https://github.com/governmentbg/opendata/blob/master/LICENSE). За opendata неща обикновено препоръчваме CC0 (Creative Commons Zero) или MIT. Повече информация за видовете лицензи може да намериш на: http://choosealicense.com/

Във footer-а на сайта е достатъчно да се укаже името на лиценза и, може би, да се линкне към `LICENSE` файла от хранилището.

/cc @mihail-ivanov

**Comment by pdpetrov** [comment]
MIT лиценз е добавен
