### ISSUE TITLE
Добавяне на линкове към хранилището с кода и лиценз за ползване на данните

### ISSUE THREAD

**Issue by mitio** [pdpetrov/data-viz#2]
Мисля, че е добра идея да се сложи един текст във футъра на тези визуализации, който да линква към хранилището и да пише нещо от рода на:

> "Визуализациите в този портал са с отворен код. [Проектът се намира тук](https://github.com/ppetrovcsr/data-viz). Всички данни и визуализации се разпространяват под лиценз ..."

Виж #1 за лиценза.

EDIT: Преди да се прави това issue, е добре да се изчисти #4.

/cc @mihail-ivanov

**Comment by pdpetrov** [comment]
Footer is updated with this info

**Comment by mitio** [comment]
Супер! Само една бележка: точката на изречението след линка "тук" слиза на нов ред ([снимка](https://www.dropbox.com/s/e72yl6v1kyzqiv9/Screenshot%202016-05-08%2020.31.28.png?dl=0)).

**Comment by pdpetrov** [comment]
Хм, зависи от големината на екрана. Бях оставил по погрешка едно допълнително празно място. Сега съм го отстранил. Надявам се е оправило

**Comment by mitio** [comment]
Да, сега е напълно окей 👍
