### ISSUE TITLE
Добавяне на линкове към суровите данни, използвани за дадена визуализация

### ISSUE THREAD

**Issue by mitio** [pdpetrov/data-viz#3]
Смятам, че е много добра идея всички сурови данни, които са използвани за визуализациите, да са изрично споменати и линкнати от страниците с визуализациите. Имам предвид CSV файловете, които директно се зареждат от D3. Например, в страницата с данни за престъпността, е добре да има линк към всеки един от CSV файловете от тук, потенциално споменавайки още веднъж какъв е лицензът за употреба на данните (виж #1):

https://github.com/ppetrovcsr/data-viz/tree/gh-pages/assets/data/crime

EDIT: Преди да се прави това issue, е добре да се изчисти #4.

**Comment by pdpetrov** [comment]
И за четирите визуализации е добавен линк. Може автоматично да се поставя линка за в бъдеще, но за момента е ок
