### ISSUE TITLE
Преместване на хранилището в организацията governmentbg?

### ISSUE THREAD

**Issue by mitio** [pdpetrov/data-viz#4]
Здрасти, Пламене,

Аз и @mihail-ivanov имаме грижата да направим статичните файлове в това хранилище публични преди 10 май.

В тази връзка, ти би ли се съгласил да преместим това хранилище в организацията governmentbg, като ти ще си запазиш пълните администраторски права над хранилището? Трябва да се има предвид и че всички owner-и в governmentbg ще имат възможност да правят неща по хранилището.

Две основни причини за преместването:
- В https://github.com/governmentbg се събират всички неща, свързани с opendata, които са по някакъв начин произлезли от държавата, а не от несвързани трети страни.
- Обмисляме варианти за публикуване на този проект под "шапката" на портала и ще е по-удобно за нас и ние да имаме достъп до кода и да правим бързи дребни корекции където се налага.

**Comment by pdpetrov** [comment]
Привет,

звучи супер :), за удобство съм ви направил collaborators, ако трябва да се правят малки промени etc.

Поздрави

**Comment by mitio** [comment]
Пламене, благодаря, че оправи нещата.

Не разбрах дали си окей хранилището да бъде преместено от твоя профил в профила на организацията https://github.com/governmentbg? Ако да, това можеш и трябва да го направиш само ти, от Settings > Transfer Ownership.

След това ще трябва да сменим линковете и да свържем хранилището с един поддомейн на opendata.government.bg, който сме подготвили специално за целта.

**Comment by pdpetrov** [comment]
Здрасти, Митьо, 
мерси за инструкциите, но не успях да се справя и по-рано с transfer-а на правата, понеже не съм админ на governmentbg. (You don’t have admin rights to governmentbg)

Конкретно това е проблемът :
https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization

Имаш ли идеи как да го осъществя по друг начин?

**Comment by mitio** [comment]
Хм, това не го знаех. Благодаря ти за линка! Може да е ново, но може и да не съм попадал преди в тази ситуация.

Преди време бях направил [това хранилище](https://github.com/governmentbg/opendata-visualizations) за [този сайт](https://opendata.government.bg/static/visualizations/dashboard.html) и мислех да ползваме него, но съм забравил, че го има :)

Тъй като вече имаме текущото хранилище, мисля, че ще е по-лесно просто да го fork-нем в governmentbg. Сега ще го направя и ще ти дам достъп до там.

**Comment by mitio** [comment]
Готово. [Това е хранилището](https://github.com/governmentbg/data-viz). Би трябвало и ти да имаш read/write достъп, ако трябва да коригираш неща.

На мен ще ми се наложи да направя някои промени в линковете във футъра и към данните, за да сочат към новото хранилище, както и да го "свържа" с домейна.

Отново, благодаря много за помощта!

**Comment by pdpetrov** [comment]
Имам да, и аз мерси :+1:  Поздрави
